# Generated by Django 3.1.1 on 2020-09-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.userbankaccount')),
            ],
        ),
    ]
